name: SKY UX CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
    tags:
      - '*.*.*'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v6
        with:
          node-version: '20.x'
      - uses: blackbaud/skyux-sdk-actions@master
        with:
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
